zookeeper:
  image: enow/zookeeper
  ports:
    - "2181:2181"
nimbus:
  image: enow/storm-nimbus
  # container_name: storm-nimbus
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  links:
    - zookeeper:zk
  volumes:
    - target:/usr/share/apache-storm/extlib
supervisor:
  image: enow/storm-supervisor
  ports:
    - "8000:8000"
  links:
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: enow/storm-ui
  ports:
    - "8080:8080"
  links:
    - nimbus:nimbus
    - zookeeper:zk
kafka:
  image: enow/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    # You should set this to the name/ip of the host that runs docker.
    # If you run docker natively on a linux box,
    # you can set this parameter to your host ip address (e.g. the IP of eth0),
    # which will allow you to access kafka from other machines in the network.
    # If you set it to your docker0 IP address you can only access kafka from the host that runs docker.
    # On mac : ifconfig en0| grep 'inet ' | cut -d " " -f2 | awk '{ print $1 }'
    # On linux : ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'
    KAFKA_ADVERTISED_HOST_NAME: 192.168.100.158
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
